[package]
name = "diecast"
version = "0.2.1"
authors = ["Kieran Eglin <kieran.eglin@gmail.com>"]

[[bin]]
path = "src/main.rs"
name = "dt"

[dependencies]
colored = "1.5.2"
fs_extra = "1.0.0"
clap = {version = "2.25.0", features = ["yaml"]}
